# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - scaled_joint_trajectory_controller

  scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - ur3e1_shoulder_pan_joint
      - ur3e1_shoulder_lift_joint
      - ur3e1_elbow_joint
      - ur3e1_wrist_1_joint
      - ur3e1_wrist_2_joint
      - ur3e1_wrist_3_joint
      - ur3e2_shoulder_pan_joint
      - ur3e2_shoulder_lift_joint
      - ur3e2_elbow_joint
      - ur3e2_wrist_1_joint
      - ur3e2_wrist_2_joint
      - ur3e2_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true