# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_scaled_joint_trajectory_controller
    - right_scaled_joint_trajectory_controller
    - left_gripper_gpio_controller
    - right_gripper_gpio_controller

  left_scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true
  right_scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true
    
  left_gripper_gpio_controller:
    type: GripperCommand
    default: true
    joints:
      - left_gripper_slider_1_joint
      - left_gripper_slider_2_joint
    default: true

  right_gripper_gpio_controller:
    type: GripperCommand
    default: true
    joints:
      - right_gripper_slider_1_joint
      - right_gripper_slider_2_joint