# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_zimmer_gripper_controller:
      type: position_controllers/GripperActionController


    right_zimmer_gripper_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_zimmer_gripper_controller:
  ros__parameters:
    joint: left_gripper_slider_1_joint
    
right_zimmer_gripper_controller:
  ros__parameters:
    joint: right_gripper_slider_1_joint