controller_manager:
  ros__parameters:
    update_rate: 500 # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    zimmer_gripper_controller:
      type: position_controllers/GripperActionController
    zimmer_activation_controller:
      type: zimmer_controllers/ZimmerActivationController

zimmer_gripper_controller:
  ros__parameters:
    default: true
    joint: actuator_1
    use_effort_interface: true
    use_speed_interface: true

zimmer_activation_controller:
  ros__parameters:
    default: true